from .clientes import gestionar_clientes
from .clientes import ver_clientes
from .clientes import agregar_cliente
from .clientes import modificar_cliente
from .clientes import eliminar_cliente
from .destinos import gestionar_destinos
from .destinos import ver_destinos
from .destinos import agregar_destino
from .destinos import modificar_destino
from .destinos import cambiar_disponibilidad_destino
from .pasajes import gestionar_pasajes
from .pasajes import ver_pasajes
from .pasajes import compra_de_pasaje
from .pasajes import cancelacion_de_pasaje
from .menu_principal import menu_principal
from .menu_principal import acerca_del_sistema